name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest torchsummary
    
    - name: Download model weights
      run: |
        if [ ! -f "best_mnist_model.pth" ]; then
          echo "Error: Model weights file not found"
          exit 1
        fi
        
    - name: Run tests
      run: |
        pytest test_mnist_model.py -v