name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision tqdm matplotlib pytest torchsummary
    
    - name: Download model weights
      run: |
        # Add commands to download model weights if stored externally
        # For now, assuming weights are in the repository
        
    - name: Run tests
      run: |
        pytest test_mnist_model.py -v 